server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/laravel?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
